#Análisis y Descomposición de señales

EJERCICIO 1: Resume lo mas que puedas en una celda los pasos imprescindibles para aplicar PCA "a mano". Comenta cada linea.

In [ ]:
from sklearn import datasets
import matplotlib.pyplot as plt
import numpy as np

iris = datasets.load_iris()
X = iris.data

# 1er Paso: Calcular la media
m = np.mean(X, axis=0)

# 2do Paso: Centrar los datos restando la media
Xm = X - m[np.newaxis, :]

# 3er Paso: Calcular la matriz de covarianza
cov_matrix = np.dot(Xm.T, Xm) / Xm.shape[0]

# 4to Paso: Calcular los autovalores y autovectores de la matriz de covarianza
evals, evecs = np.linalg.eigh(cov_matrix)

# 5to Paso: Proyectar los datos centrados en el nuevo espacio PCA
Xpca = np.dot(evecs.T, Xm.T).T

print(Xpca)

[[ 2.26243707e-03  2.79148276e-02  3.19397247e-01  2.68412563e+00]
 [ 9.90265503e-02  2.10464272e-01 -1.77001225e-01  2.71414169e+00]
 [ 1.99683897e-02 -1.79002563e-02 -1.44949426e-01  2.88899057e+00]
 [-7.55758166e-02 -3.15593736e-02 -3.18298979e-01  2.74534286e+00]
 [-6.12585926e-02 -9.00792406e-02  3.26754513e-01  2.72871654e+00]
 [-2.42008576e-02 -1.68677658e-01  7.41330449e-01  2.28085963e+00]
 [-4.81431065e-02 -2.57892158e-01 -8.94613845e-02  2.82053775e+00]
 [-4.52978706e-02  2.18793179e-02  1.63384960e-01  2.62614497e+00]
 [-2.67447358e-02 -2.07595703e-02 -5.78311754e-01  2.88638273e+00]
 [-5.62954013e-02  1.97632725e-01 -1.13774246e-01  2.67275580e+00]
 [-1.50199245e-02  7.53180094e-02  6.45068899e-01  2.50694709e+00]
 [-1.56379208e-01 -1.02150260e-01  1.47299392e-02  2.61275523e+00]
 [-7.88791149e-03  2.06844430e-01 -2.35112000e-01  2.78610927e+00]
 [-2.16798118e-02 -6.12996725e-02 -5.11394587e-01  3.22380374e+00]
 [ 1.59209718e-01  1.51627524e-01  1.17876464e+00  2.64475039e

EJERCICIO 3: Aplica PCA usando sklearn a los datos de Boston. Explica cada paso.

In [ ]:
from sklearn.datasets import load_boston
from sklearn import datasets
import matplotlib.pyplot as plt
import numpy as np

boston = datasets.load_boston()
X = boston.data

# 1er Paso: Calcular la media
m = np.mean(X, axis=0)

# 2do Paso: Centrar los datos restando la media
Xm = X - m[np.newaxis, :]

# 3er Paso: Calcular la matriz de covarianza
cov_matrix = np.dot(Xm.T, Xm) / Xm.shape[0]

# 4to Paso: Calcular los autovalores y autovectores de la matriz de covarianza
evals, evecs = np.linalg.eigh(cov_matrix)

# 5to Paso: Proyectar los datos centrados en el nuevo espacio PCA
Xpca = np.dot(evecs.T, Xm.T).T

print(Xpca)

EJERCICIO 4: ¿Que otras descomposiciones hay en "sklearn.decomposition" que conozcas? Elige una, pruébala y explícala.

https://scikit-learn.org/stable/modules/classes.html#m

In [ ]:
from sklearn.decomposition import NMF
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
X = iris.data

# Creando el modelo de Factorización de Matrices No Negativas
nmf = NMF(n_components=2, init='random', random_state=42)

# Ajustando y transformando los datos
X_nmf = nmf.fit_transform(X)

# Imprimiendo los resultados
print(X_nmf)

[[1.52995118 0.14186618]
 [1.39288444 0.20725808]
 [1.40311201 0.14017235]
 [1.34566372 0.22203649]
 [1.5304409  0.12583602]
 [1.62718859 0.22882307]
 [1.40827687 0.16086705]
 [1.48175101 0.18870491]
 [1.27700775 0.21063774]
 [1.40915482 0.21274053]
 [1.6178383  0.15537334]
 [1.43404056 0.21951349]
 [1.3794509  0.18952846]
 [1.31103946 0.07391016]
 [1.78166997 0.01696555]
 [1.80198273 0.09548878]
 [1.66418108 0.08872145]
 [1.52415356 0.15748739]
 [1.67095881 0.23344886]
 [1.57406809 0.15074755]
 [1.54017941 0.26718939]
 [1.54854959 0.18029051]
 [1.48162494 0.        ]
 [1.44537219 0.3216495 ]
 [1.4062962  0.3245897 ]
 [1.39361936 0.2794173 ]
 [1.46090765 0.25497273]
 [1.53993422 0.179     ]
 [1.52946146 0.15789634]
 [1.37536764 0.24524856]
 [1.37487792 0.26127872]
 [1.54708042 0.22838099]
 [1.66405713 0.07984832]
 [1.744922   0.05284762]
 [1.4033572  0.22836174]
 [1.47005361 0.11147219]
 [1.61612395 0.11527444]
 [1.51700735 0.1081064 ]
 [1.30597676 0.16169059]
 [1.50098217 0.19081333]


ValueError: cannot reshape array of size 2098176 into shape (170,256,4,4)

TypeError: camera() takes 0 positional arguments but 1 was given